### ISSUE TITLE
Unpkg provider: Still using HTTP? 

### ISSUE THREAD

**Issue by Abhith** [aspnet/LibraryManager#491] opened 2019-06-18 06:37 UTC
### Functional impact
Unable to download libraries from unpkg in an environment where network firewall will allow only HTTPS requests. 

### Minimal repro steps
Using VS 16.1.3, attempt to restore a package from unpkg.

### Expected result
I would expect the restore to work.

### Actual result
Build failed. "xxx library could not resolved by the "unpkg" provider".

### Further technical details
Using fiddler, I confirmed that libman is requesting HTTP by default. And the network firewall is responding with 403.

A similar issue mentioned in #430 which resolved by #436. But that update seems like not LIVE.

**Comment by saluton-mundo** [comment] 2019-07-31 10:14
Confirmed. Libman is using HTTP for requests to unpkg and this is returning 301. Visual Studio then abandons the build and returns LIB002 "... library could not be resolved by the unpkg provider"

![image](https://user-images.githubusercontent.com/7760994/62203943-14f27600-b384-11e9-9fa2-e446411b730e.png)

**Comment by sfg11** [comment] 2019-11-12 17:34
Any updates on this? Trying to use bootstrap in a prod env and cant get around the error:

` libman.json : error LIB002: The "bootstrap@4.3.0" library could not be resolved by the "unpkg" provider`

**Comment by jimmylewis** [comment] 2020-05-05 06:41
This was addressed with #436.  Since it was checked in only for after the 2.0 switch (for VS2019), users still on VS2017 may still see this; however (and unfortunately) this wouldn't meet the servicing bar for VS2017.  Closing this until I hear of new reports (but I haven't seen any issues with this).

**Closed by jimmylewis** 2020-05-05 06:41 UTC
Labels: P2
