### ISSUE TITLE
Related Libraries operations are not faded during task manager working on restoring libraries.

### ISSUE THREAD

**Issue by YangLyu89** [aspnet/LibraryManager#149] opened 2018-06-12 01:48 UTC
### Functional impact
User can still do other libraries operations when restoring libraries

### Minimal repro steps
1. Right click on libman.json, choose restore client-side libraries
2. Observing the task is running.
3. right click on libman.json

### Expected result
Operations like clean client-side libraries should be faded

### Actual result
It's not changed

**Comment by jodavis** [comment] 2018-06-12 12:54
Duplicate of https://github.com/aspnet/LibraryManager/issues/118

**Closed by jodavis** 2018-06-12 12:54 UTC
