### ISSUE TITLE
libman.json added to two different project single solution doesn't work 

### ISSUE THREAD

**Issue by ns8482e** [aspnet/LibraryManager#667] opened 2022-01-09 15:38 UTC
### Describe the bug
I am working o modular application where each project within a solution is separate module. I am using libman.json to manage client side library required within each project. However updating entries in one projects updates client library in another project.

### To Reproduce
1. Create two projects 'Project A' and 'Project B' in same solution
2. Create  `Project A\libman.json` with `bootstrap` with destination `Project A\wwwroot\lib\bootstrap`
3. Create  `Project B\libman.json` with `jquery` with destination `Project B\wwwroot\lib\jquery`
4. Notice that `jquery` and `bootstrap` both are available in both projects, removing entry in one file also removes content from another project.

### Expected behavior
Project A should have only bootstrap and Project B should have only jquery.

### Screenshots
N/A

### Additional context
Using Visual Studio 2022 Pro.

**Comment by jimmylewis** [comment] 2022-01-09 18:38
This is a duplicate of #638, and a fix will be included in the VS 17.1 Preview 3 release.

**Closed by jimmylewis** 2022-01-09 18:38 UTC
