### ISSUE TITLE
Request: Destination path pattern

### ISSUE THREAD

**Issue by TristanApc** [aspnet/LibraryManager#438] opened 2019-02-01 13:52 UTC
It would be incredibly useful to support some kind of pattern for the destination path. This would result in less error prone writing of libman.json and could make the migration to LibraryManager faster. In the context that I just performed a migration from Bower and most of the libraries that was in used in the project had a common, yet unique destination pattern.

For example, if you have dozens of libraries that you each want to put in a path of the following format:

``wwwroot/lib/{nameOfLibrary}/dist`` at the moment you have to write the destination for every libraries since you can't use the defaultDestination as every destination are unique.

### Minimal repro steps
libman.json with the following contents.

```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "destinationPattern": "wwwroot/lib/{library}/dist/"
  "libraries": [
    {
      "destination": "wwwroot/lib/eonasdan-bootstrap-datetimepicke/build/"
      "library": "eonasdan-bootstrap-datetimepicker@4.17.47"
    },
    {
        "library": "jquery@2.1.4"
    }
  ]
}
```

### Expected result
A destination of the following form:

```
wwwroot/
     lib/
          eonasdan-bootstrap-datetimepicker/
               build/
                    ......

          jquery/
               dist/
                    ......

```

**Comment by RobJohnston** [comment] 2020-08-27 01:39
Duplicate of #57 , but this has a better description.

**Comment by CodeChief** [comment] 2021-08-10 10:13
Any progress on this. Seems like a pretty basic feature to implement. Having all the scripts and content from libraries dumped in the same path will surely lead to naming conflicts besides looking like a big mess.

Is this tool still in active development???

**Comment by jimmylewis** [comment] 2024-10-02 06:39
This is addressed by #759 which adds support for `[Name]` and `[Version]` tokens in the defaultDestination

**Closed by jimmylewis** 2024-10-02 06:39 UTC
Labels: Feature Request

**Comment by spencer-wcri** [comment] 2025-02-07 21:14
Any timeline for a release with this feature?

**Comment by jimmylewis** [comment] 2025-03-22 19:13
Should be in the 3.0.71 packages, or current Visual Studio builds.
