### ISSUE TITLE
Method not found exception: get_CacheFolder

### ISSUE THREAD

**Issue by jwillmer** [aspnet/LibraryManager#480] opened 2019-05-13 14:18 UTC
Tried to build my solution on a new PC (with updated nuget packages). 

Old version: 1.0.172
Installed version 2.0.48

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.String Microsoft.Web.LibraryManager.CacheService.get_CacheFolder()'.
   at Microsoft.Web.LibraryManager.Build.HostInteraction.get_CacheDirectory()
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsProvider.get_CacheFolder()
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsCatalog..ctor(CdnjsProvider provider)
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsProvider.GetCatalog()
   at Microsoft.Web.LibraryManager.Extensions.<IsValidAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.Extensions.<IsValidAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<ValidatePropertiesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<GetLibrariesErrorsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<GetManifestErrorsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.Manifest.<GetValidationResultsAsync>d__31.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'System.String Microsoft.Web.LibraryManager.CacheService.get_CacheFolder()'.
   at Microsoft.Web.LibraryManager.Build.HostInteraction.get_CacheDirectory()
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsProvider.get_CacheFolder()
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsCatalog..ctor(CdnjsProvider provider)
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsProvider.GetCatalog()
   at Microsoft.Web.LibraryManager.Extensions.<IsValidAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.Extensions.<IsValidAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<ValidatePropertiesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<GetLibrariesErrorsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.LibrariesValidator.<GetManifestErrorsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.Manifest.<GetValidationResultsAsync>d__31.MoveNext()<---	Maranics.Checklist.Management.Web		0	
```

**Comment by jwillmer** [comment] 2019-05-13 14:21
Clear solution and rebuild fixes the issue.

**Comment by NikolayIT** [comment] 2019-05-17 06:35
Didn't fix it in my case. I got the same `System.MissingMethodException: Method not found: 'System.String Microsoft.Web.LibraryManager.CacheService.get_CacheFolder()'.`

**Comment by jwillmer** [comment] 2019-05-17 07:12
Yes, I also still have it. But it only occurs when I deploy to Azure via "WebDeploy". Building locally or deploying via FTP works.

**Comment by jimmylewis** [comment] 2019-05-22 18:53
Closing this as a duplicate of #481, since that one has [more details](https://github.com/aspnet/LibraryManager/issues/481#issuecomment-494921049) about the cause.

**Closed by jimmylewis** 2019-05-22 18:53 UTC
Labels: P1
