### ISSUE TITLE
In .NET Core, libMan install 'Failed to download resource'

### ISSUE THREAD

**Issue by chjatala** [aspnet/LibraryManager#476] opened 2019-05-02 08:30 UTC
Hello,

I am working with .NET core in Ubuntu 18.04 behind a proxy server. When I try to install a library using 'libMan' utility (version 1.0.172+g2a33cb3eeb) got ''Failed to download resource' error message.

**Tried command:** libman install @aspnet/signalr -p unpkg -d wwwroot/lib/signalr --files dist/browser/signalr.js --files dist/browser/signalr.min.js

**Error message:** Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://api.npms.io/v2/search?q=signalr+scope:aspnet" at Microsoft.Web.LibraryManager.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken) at Microsoft.Web.LibraryManager.Extensions.GetJsonObjectViaGetAsync(IWebRequestHandler webRequestHandler, String url, CancellationToken cancellationToken) at Microsoft.Web.LibraryManager.Providers.Unpkg.NpmPackageSearch.GetPackageNamesWithScopeAsync(String searchTerm, CancellationToken cancellationToken) at Microsoft.Web.LibraryManager.Providers.Unpkg.NpmPackageSearch.GetPackageNamesAsync(String searchTerm, CancellationToken cancellationToken) at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgCatalog.SearchAsync(String term, Int32 maxHits, CancellationToken cancellationToken) [LIB002]: The "@aspnet/signalr" library could not be resolved by the "unpkg" provider

**Apparently present version of libman utility does not offer 'config' command for configuring proxy settings. Does anyone know a workaround to this proxy issue?**

**Comment by Roman-Tarasiuk** [comment] 2019-05-02 08:58
It has to be supported – see pull request #474.

**Comment by chjatala** [comment] 2019-05-02 09:30
The libman version **1.0.172+g2a33cb3eeb** does not have  'config'. Here is output of **libman --help**
 1.0.172+g2a33cb3eeb

Usage: libman [options] [command]

Options:
  --help|-h  Show help information
  --version  Show version information

Commands:
  cache      List or clean libman cache contents
  clean      Deletes all library files defined in libman.json from the project
  init       Create a new libman.json
  install    Add a library definition to the libman.json file, and download the library to the specified location
  restore    Downloads all files from provider and saves them to specified destination
  uninstall  Deletes all files for the specified library from their specified destination, then removes the specified library definition from libman.json
  update     Updates the specified library

Use "libman [command] --help" for more information about a command.

**Comment by Roman-Tarasiuk** [comment] 2019-05-02 15:00
@jimmylewis, I see the same message after updating (and even uninstall\install) the <code>libman</code> tool.
I use the <code>dotnet tool install --global Microsoft.Web.LibraryManager.Cli</code> command to install the tool into the C:\Users\username\\.dotnet\tools directory, so maybe it (the <code>dotnet</code> tool) uses another, not updated source...

**Comment by jimmylewis** [comment] 2019-05-02 20:45
I'm working on getting the updated package pushed to NuGet, which will contain the new `libman config` command.  I believe the new package version will be 2.0.48 once it's up.

I'm closing this issue for now as it's a dupe of #399.  I'll resolve that issue when the new package is available.

**Closed by jimmylewis** 2019-05-02 20:45 UTC

**Comment by chjatala** [comment] 2019-05-03 07:11
@jimmylewis thanks and looking forward to find my way out of this **bottle-neck** with the new package.

**Comment by Roman-Tarasiuk** [comment] 2019-05-03 13:39
@chjatala, you can try to apply my workaround solution as described in https://github.com/aspnet/LibraryManager/issues/399#issuecomment-472760343.

**Comment by Roman-Tarasiuk** [comment] 2019-05-17 09:47
@chjatala, the new version is available so you can update the <b>libman</b> (using the <code>dotnet tool update --global Microsoft.Web.LibraryManager.Cli</code>) command and try to use it as described in the #399. In my case, proxy login is 'domain\username'.
