### ISSUE TITLE
Request: File Pattern Matching

### ISSUE THREAD

**Issue by flemingtech** [aspnet/LibraryManager#388] opened 2018-10-22 19:55 UTC
It would be very useful if pattern matching, even simple ones, could be used in choosing files. This would be especially useful when trying to pull in a large amount of files that are all contained in a library's sub-folder.

### Minimal repro steps
libman.json with the following contents.

```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "foundation@6.4.3",
      "files": [ "js/*" ],
      "destination": "Scripts/Foundation"
    }
  ]
}
```

### Expected result
All files in the '/js' folder of the library is copied to the destination folder.

### Actual result
Error that lists the 'actual' available files.

**Comment by jimmylewis** [comment] 2020-01-02 08:04
This is a dupe of #42 and was addressed in #534

**Closed by jimmylewis** 2020-01-02 08:04 UTC
Labels: Feature Request
