### ISSUE TITLE
Unpkg provider: folders are not deleted after delete the library in libman.json

### ISSUE THREAD

**Issue by YangLyu89** [aspnet/LibraryManager#152] opened 2018-06-12 02:16 UTC
### Minimal repro steps
1. Delete a library for unpkg provider in libman.json (for example, jquery)
2. restore the libraries

### Expected result
The libraries downloaded get deleted

### Actual result
The files are deleted, the folders are not (including sub-folders)

**Comment by jimmylewis** [comment] 2018-06-12 08:31
Dupe of #119

**Closed by jimmylewis** 2018-06-12 08:31 UTC
