### ISSUE TITLE
Cannot open Client-Side Package Manager

### ISSUE THREAD

**Issue by scottaddie** [aspnet/LibraryManager#593] opened 2020-07-23 17:49 UTC
Issue moved from https://github.com/dotnet/AspNetCore.Docs/issues/19295. Originally opened by @smiller7812.

> Anyone know why "Client-Side" Package Manager will not come up?
> When I click on Manage client-side library, libman.json pops up.
> Cannot get the GUI.
> 
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 1d69ef46-689c-33d0-c86b-078c8172c480
> * Version Independent ID: 519af8ab-78e5-88c9-f268-431f417eca73
> * Content: [Use LibMan with ASP.NET Core in Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-3.1)
> * Content Source: [aspnetcore/client-side/libman/libman-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/libman/libman-vs.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-clientside**
> * GitHub Login: @scottaddie
> * Microsoft Alias: **scaddie**

**Comment by jimmylewis** [comment] 2020-07-23 18:23
This is a duplicate of #411.

The TL;DR summary is that the Add Client-Side Library command launches the wizard (which only supports adding a new library), and the Manage Client-Side Packages opens the .json file which lets you view all the library settings for the project.

**Closed by jimmylewis** 2020-07-23 18:24 UTC
