### ISSUE TITLE
Add ability to grab scss files

### ISSUE THREAD

**Issue by mattfraley1** [aspnet/LibraryManager#78] opened 2018-05-08 14:59 UTC
I generally use bootstrap or foundation scss files. I keep these on a network share, so I can load them with this extension using the filesystem provider but not very well. For example:

```
{
      "provider": "filesystem",
      "id": "[network location]\\Bootstrap\\bootstrap-4.1.0\\scss\\",
      "path": "wwwroot/lib/bootstrap/scss/",
      "files": [
        "bootstrap-grid.scss",
        "bootstrap-reboot.scss",
        ...
```
First, there are 38 files in this folder, and it would be much nicer to just type *. 

Second, there are two subfolders, mixins and utilities. Those each need there own entry because currently this extension won't grab items in subfolders. 

What would be nice is something like this:
```
{
      "provider": "filesystem",
      "id": "[network location]\\Bootstrap\\bootstrap-4.1.0\\scss\\",
      "path": "wwwroot/lib/bootstrap/scss/",
      "files": [
           **/*
      ]
```
This would work fine for me, but others may prefer an online provider. Maybe a provider such as unpkg would work for that.

**Comment by nickalbrecht** [comment] 2018-05-08 17:08
I believe if you leave the files part out entirely, and just use the source and destination paths, you get the equivalent of pulling in all files?

**Comment by mattfraley1** [comment] 2018-05-08 20:25
Ah sure enough, you do get all the files in that directory, but not sub directories. Still that is much cleaner than listing all 83 or so files individually. A step in the right direction.

**Comment by jimmylewis** [comment] 2018-05-09 18:29
Support for globbing patterns would improve capabilities of the "files" collection considerably for when you want a subset of files but it would be a pain to list them all out.

@justcla I think we talked about this once before.  Can you put this on the backlog?

**Comment by justcla** [comment] 2018-05-09 23:52
Thanks for raising the issue @mattfraley1 
As @nickalbrecht mentioned, you can leave out the files to get all the files in the library. And when you do this with the CDNJS provider, it pulls down all files in all directories.
As you pointed out, the filesystem provider only brings down files from the current directory - and not any of the subdirectories. Personally, I see this behavior as weird and inconsistent with the other provider. Perhaps we should change the filesystem provider behavior so that all files **and folders** are fetched if no files are specified.

Separately, supporting file globbing would be very cool! I'll add it to the backlog.

**Comment by justcla** [comment] 2018-05-09 23:56
Update: I am raising a bug for the filesystem provider to return all files **and folders** in the prescribed location.

**Comment by scotato** [comment] 2019-01-29 20:56
@justcla Did the files and folders issue get created? Curious what the status of this is.

**Comment by jimmylewis** [comment] 2019-11-13 07:08
Closing this as a 1/2 dupe of #42 and 1/2 dupe of #350.  You'll be able to use * to match all files in the directory per #42, but the filesystem provider still doesn't handle recursive cases.

**Closed by jimmylewis** 2019-11-13 07:08 UTC
