### ISSUE TITLE
Discussion: Include a jsDelivr provider

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#344] opened 2018-08-08 17:55 UTC
User @Drgy submitted a PR #338 to Add the jsDelivr provider to Library Manager.

Need to determine:
Should Library Manager include jsDelivr as a provider?
If so, should it replace the existing UnPkg provider?

**Comment by justcla** [comment] 2018-08-08 17:56
Question:
What's the main benefit of using jsDelivr over UnPkg?

**Comment by Tsabo** [comment] 2018-08-23 13:32
Should it be included, absolutely. Why? Because, any option other than UnPkg is a better option. I spent two hours last night trying to install one package and it still isn't installed. I'm back at it this morning trying it again and watching it fail over and over again. The twenty-five second timeout on UnPkg is dreadful.

![image](https://user-images.githubusercontent.com/2382302/44523588-fa0d8100-a69f-11e8-9fa7-95ddc6a0311c.png)

It would also be nice to be able to have a provider that can pull from our private MyGet NPM/Bower feeds. Another idea would be to have a provider for content only NuGet packages, for example DevExtreme.Web.

**Comment by MartinKolarik** [comment] 2018-08-23 17:47
>Because, any option other than UnPkg is a better option.

And you haven't even seen some of the more funny issues yet 😆 

>It would also be nice to be able to have a provider that can pull from our private MyGet NPM

We are currently considering adding support for private npm/GitHub packages to jsDelivr.

**Comment by nwoolls** [comment] 2018-10-29 18:09
@Tsabo I don't want to digress too far here, but did you find a solution to the problem with timeouts, `ResourceDownloadException` and the UnPkg provider? I'm in the same boat - waiting for an excruciating amount of time before the install eventually fails for larger libraries. The file it fails on is different each time (so far), and if I browse to the URL in the stack trace I am able to see the file exists.

**Comment by AdamWillden** [comment] 2018-11-12 15:05
@justcla @jimmylewis the PR pertaining to this was merged 3 days ago, what does that mean for this issue (should it be closed?)

Also when do we expect to be able to use jsDelivr? Is there a release we need to wait for?

/cc @nwoolls

**Comment by jimmylewis** [comment] 2018-11-16 00:08
@AdamWillden Yes, this issue should be closed.  Thanks for pointing it out. :)

In-VS support for jsDelivr won't come until VS2019 Preview 2; however, if you build it yourself up to commit `2a33cb3eeb98acdf85`, you should be able install that build on your VS2017 instance.  *If you are sharing with team members, they all need to do the same, or else their non-jsDelivr-supporting versions will fail to restore.*

We're looking into releasing the CLI and MSBuild packages as well, so that we can enable jsDelivr on CI, but it has the same pitfall.

/cc @jodavis

**Closed by jimmylewis** 2018-11-16 00:08 UTC
Labels: discussion

**Comment by AdamWillden** [comment] 2018-12-11 10:30
@jimmylewis Thanks for the info, it's a shame that we're to wait until VS2019 but as you say it's CI that's the important thing here. Is there anywhere I can track the CLI update? I could use tooling to swap the libman config options in CI (so that we can get reliable builds).

**Comment by jimmylewis** [comment] 2018-12-21 17:03
@AdamWillden we updated the CLI and Build packages today (version 1.0.172), which contains the jsdelivr provider.  You'll still get errors editing libman.json in VS, but this should unblock you for CI scenarios.

**Comment by AdamWillden** [comment] 2019-01-02 11:13
@jimmylewis thanks, confirmed we can do a find replace on our CI to change `unpkg -> jsdelivr`. This has drastically improved our build times and no doubt reliability too.
